name: Java CI for CollinearPoints

on:
  push:
    paths:
      - 'Lecture6/collinear/**'
      - 'Lecture89/**'
  pull_request:
    paths:
      - 'Lecture6/collinear/**'
      - 'Lecture89/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Shell Script for Compilation and Testing
        run: ./compile_and_test.sh

