name: Java CI for CollinearPoints

on:
  push:
    paths:
      - 'Lecture6/collinear/**'
  pull_request:
    paths:
      - 'Lecture6/collinear/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create lib directory and Download Dependencies
        run: |
          mkdir -p lib
          wget -q -O lib/algs4.jar https://algs4.cs.princeton.edu/code/algs4.jar
          wget -q -O lib/junit-jupiter-api.jar https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.8.1/junit-jupiter-api-5.8.1.jar
          wget -q -O lib/junit-jupiter-engine.jar https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.8.1/junit-jupiter-engine-5.8.1.jar
          wget -q -O lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.1/junit-platform-console-standalone-1.8.1.jar

      - name: Compile Java Code
        run: javac -cp ".:lib/algs4.jar:lib/junit-jupiter-api.jar:lib/junit-jupiter-engine.jar" Lecture6/collinear/*.java

      - name: Run Tests
        run: java -cp ".:lib/algs4.jar:lib/junit-jupiter-api.jar:lib/junit-jupiter-engine.jar:." -jar lib/junit-platform-console-standalone.jar --select-class Lecture6.collinear.TestCollinear
